[tool.poetry]
name = "datto"
version = "0.2.6"
description = "Data Tools (Dat To)"
authors = ["kristiewirth <kristie.ann.wirth@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.6.7"
ipython = "^7.8"
pytest = "^5.2"
black = "^19.10b0"
pylint = "^2.5.0"
pandas = "^1.0.4"
notebook = "^6.0.3"
spacy = "^2.2.4"
s3fs = "^0.4.2"
psycopg2-binary = "^2.8.5"
kafka-python = "^2.0.1"
python-json-logger = "^0.1.11"
python-dotenv = "^0.13.0"
sklearn = "^0.0"
xgboost = "^1.1.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"